Update README.md
JGVR/PortfolioApi pull request #10
Opened 2024-06-26 17:36 UTC by JGVR

updated the data design section of the ReadMe. Also, modify the UML diagrams for both the collection and data classes

2024-06-28 13:21 UTC, hecvasro requested changes

2024-06-28 13:21 UTC, hecvasro commented on README.md
> +PortfolioAPI is a RESTful service designed to seamlessly integrate with MongoDB, enabling efficient CRUD operations across various collections. It serves as the backbone for user interfaces that disp
```suggestion
PortfolioAPI is a RESTful service designed to seamlessly integrate with MongoDB, enabling efficient CRUD operations across various collections. It serves as the backbone for user interfaces that display comprehensive portfolio information, including work experiences and projects, tailored for individuals looking to showcase their professional journey. Unique to our API is the integration of a sophisticated Chatbot, powered by OpenAI's latest GPT-4o model, which acts as a personal assistant, enriching user interaction with instant, intelligent responses to inquiries.
```

I don't think you have to provide these lower-level details in the project's summary.

2024-06-28 21:18 UTC, JGVR commented on README.md
> +PortfolioAPI is a RESTful service designed to seamlessly integrate with MongoDB, enabling efficient CRUD operations across various collections. It serves as the backbone for user interfaces that disp
I made the changes we discussed during our call today. Please review and approve if all looks good @hecvasro

2024-07-03 14:52 UTC, hecvasro approved these changes
@JGVR, looks good to me!

2024-07-03 14:52 UTC, hecvasro commented on README.md
> +* LANGCHAIN_API_KEY
To which file should I add these env vars?

2024-07-08 00:09 UTC, merged